
---
apiVersion: v1
kind: Service
metadata:
  name: new-service
  labels:
    author: intelliqit
spec:
  type: LoadBalancer
  selector:
    author: intelliqit
    type: proxy
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30008
...

